# Generated by Django 4.2.3 on 2023-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('p_date', models.DateField()),
            ],
        ),
    ]
