# Generated by Django 4.2.3 on 2023-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderstatus',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(default='')),
                ('updatedesc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
